const API_BASE = "http://localhost:8080";

async function requestJson(path, options = {}, fallbackMessage = "요청 실패") {
  try {
    const res = await fetch(`${API_BASE}${path}`, options);
    if (!res.ok) {
      let detail = "";
      try {
        const payload = await res.json();
        detail = payload?.detail ? `: ${payload.detail}` : "";
      } catch {
        detail = "";
      }
      throw new Error(`${fallbackMessage}${detail}`);
    }
    return res.json();
  } catch (error) {
    if (error instanceof TypeError && String(error.message).includes("Failed to fetch")) {
      throw new Error("백엔드 서버 연결에 실패했습니다. 서버 실행 상태와 CORS 설정을 확인해 주세요.");
    }
    throw error instanceof Error ? error : new Error(fallbackMessage);
  }
}

export async function createJob(payload) {
  return requestJson(
    "/jobs",
    {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
    },
    "작업 생성 실패"
  );
}

export async function getJob(jobId) {
  return requestJson(`/jobs/${jobId}`, {}, "작업 조회 실패");
}

export async function getArtifacts(jobId) {
  return requestJson(`/jobs/${jobId}/artifacts`, {}, "아티팩트 조회 실패");
}

export async function upsertDataset(payload) {
  return requestJson(
    "/tools/dataset",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "데이터셋 저장 실패"
  );
}

export async function getDatasetStats() {
  return requestJson("/tools/dataset/stats", {}, "데이터셋 통계 조회 실패");
}

export async function getDatasetPreview(datasetType, options = {}) {
  const params = new URLSearchParams();
  if (options.limit) params.set("limit", String(options.limit));
  if (options.query) params.set("query", options.query);
  const queryString = params.toString();
  const path = `/tools/dataset/${datasetType}/preview${queryString ? `?${queryString}` : ""}`;
  return requestJson(path, {}, "데이터셋 미리보기 조회 실패");
}

export async function validatePythonCode(payload) {
  return requestJson(
    "/tools/dataset/python/validate",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "Python 코드 검증 실패"
  );
}

export async function autoGenerateDataset(payload) {
  return requestJson(
    "/tools/dataset/auto-generate",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "자동 데이터셋 생성 실패"
  );
}

export async function generateRawPromptPool(payload) {
  return requestJson(
    "/tools/dataset/raw-prompts/generate",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "Raw Prompt 풀 생성 실패"
  );
}

export async function getRawPromptPool() {
  return requestJson("/tools/dataset/raw-prompts", {}, "Raw Prompt 풀 조회 실패");
}

export async function consumeRawPromptPool(payload) {
  return requestJson(
    "/tools/dataset/raw-prompts/consume",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "Raw Prompt 풀 소비 실패"
  );
}

export async function restoreRawPromptPool(payload) {
  return requestJson(
    "/tools/dataset/raw-prompts/restore",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    },
    "Raw Prompt 풀 복원 실패"
  );
}

export async function getSavedRawPromptPools() {
  return requestJson("/tools/dataset/raw-prompts/saved", {}, "저장된 Raw Prompt 풀 목록 조회 실패");
}

export async function loadSavedRawPromptPool(filename) {
  return requestJson(
    `/tools/dataset/raw-prompts/load/${encodeURIComponent(filename)}`,
    { method: "POST" },
    "저장된 Raw Prompt 풀 불러오기 실패"
  );
}

export async function streamLmStudioChat({ payload, onDelta, onError, signal }) {
  const res = await fetch(`${API_BASE}/tools/lm-studio/openai-chat-stream`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
    signal
  });

  if (!res.ok) {
    let detail = "";
    try {
      const errorPayload = await res.json();
      detail = errorPayload?.detail ? `: ${errorPayload.detail}` : "";
    } catch {
      detail = "";
    }
    throw new Error(`LM Studio 스트리밍 요청 실패${detail}`);
  }
  if (!res.body) {
    throw new Error("브라우저가 스트리밍 응답을 지원하지 않습니다.");
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  function handleEventBlock(block) {
    const dataLines = block
      .split(/\r?\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart());
    if (dataLines.length === 0) return false;

    const data = dataLines.join("\n").trim();
    if (!data) return false;
    if (data === "[DONE]") return true;

    try {
      const parsed = JSON.parse(data);
      if (parsed?.error) {
        onError?.(parsed.error.message ?? "LM Studio 스트리밍 오류");
        return false;
      }
      const delta = parsed?.choices?.[0]?.delta ?? {};
      const content = delta.content ?? "";
      if (content) onDelta?.(content);
    } catch {
      // Ignore malformed keep-alive or vendor-specific event data.
    }
    return false;
  }

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    const blocks = buffer.split(/\r?\n\r?\n/);
    buffer = blocks.pop() ?? "";
    for (const block of blocks) {
      if (handleEventBlock(block)) return;
    }
  }

  buffer += decoder.decode();
  if (buffer.trim()) {
    handleEventBlock(buffer);
  }
}

export async function subscribeLmStudioLiveAnswer({ onEvent, signal }) {
  const res = await fetch(`${API_BASE}/tools/lm-studio/live-answer/events`, { signal });
  if (!res.ok) {
    throw new Error("LM Studio Live Answer 구독 실패");
  }
  if (!res.body) {
    throw new Error("브라우저가 스트리밍 응답을 지원하지 않습니다.");
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  function handleEventBlock(block) {
    const dataLines = block
      .split(/\r?\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart());
    if (dataLines.length === 0) return;

    const data = dataLines.join("\n").trim();
    if (!data) return;
    try {
      onEvent?.(JSON.parse(data));
    } catch {
      // Ignore malformed keep-alive or partial event data.
    }
  }

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    const blocks = buffer.split(/\r?\n\r?\n/);
    buffer = blocks.pop() ?? "";
    for (const block of blocks) {
      handleEventBlock(block);
    }
  }

  buffer += decoder.decode();
  if (buffer.trim()) {
    handleEventBlock(buffer);
  }
}
